# Generated by Django 4.1.6 on 2023-02-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding_Cops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('cost', models.CharField(blank=True, max_length=20, null=True)),
                ('length', models.CharField(blank=True, max_length=300, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('instructor', models.CharField(blank=True, max_length=300, null=True)),
                ('course_image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('tag_course', models.ManyToManyField(blank=True, to='Coding_Cops.courses')),
                ('tag_profile', models.ManyToManyField(blank=True, to='Coding_Cops.profiles')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
    ]
