# Generated by Django 4.1.6 on 2023-02-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding_Cops', '0002_courses_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(default='', max_length=300),
        ),
    ]
