# Generated by Django 4.1.6 on 2023-02-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding_Cops', '0008_alter_technologies_tech_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='my_tags',
            field=models.ManyToManyField(to='Coding_Cops.technologies'),
        ),
    ]
